#!/usr/bin/env python

"""Generates a configurable projection schema
"""

from __future__ import unicode_literals
import os
import sys

import click

import json

import schematics

from projnorm import settings, configreader, template


@click.command()
@click.option('-c', '--config', 'config_fp', type=click.File('rb'),
              required=True, help='Path to schematic configuration')
@click.option('--sort-keys/--no-sort-keys', default=True,
              help='Sort JSON keys? (Recommended)')
@click.option('-i', '--indent', type=click.INT, default=4,
              help='JSON output indentation level')
@click.argument('destination', type=click.File('w'), required=True)
def generate_schematic(config_fp, destination, sort_keys, indent):
    """Generates a schema from given template and configuration.
    """

    config = configreader.read_from_file(config_fp)

    # render schematic template
    tpl = template.get_template()
    rendered = tpl.render({
        'config': config,
        'id_systems': settings.ID_SYSTEMS,
    })

    # re-read json data for cleanup,
    # then write to final destination
    json.dump(json.loads(rendered),
              destination,
              indent=indent,
              sort_keys=sort_keys)


if __name__ == '__main__':
    generate_schematic()
