#!/usr/bin/env python

"""Generates a configurable projection schema
"""

from __future__ import unicode_literals
import os
import sys

import click

import json

import schematics

from projnorm import settings, template


QUIET = 0
LOUD = 1

@click.command()
@click.option('-v', '--verbosity', type=click.INT, default=0)
@click.argument('destination', type=click.File('w'), required=True)
def generate_schematic(verbosity, destination):
    """Generates a schema from given template and configuration.
    """

    config = settings.DEFAULT_CONFIG

    if verbosity > QUIET:
        click.echo('Batting categories: {}'.format(
                   ', '.join(config['components']['batting'])))
        click.echo('Pitching categories: {}'.format(
                   ', '.join(config['components']['pitching'])))

    tpl = template.get_template()

    # render schematic template
    rendered = tpl.render({
        'config': config,
        'id_systems': settings.ID_SYSTEMS,
    })

    rendered = rendered.strip()

    # write output
    if verbosity > QUIET:
        click.echo('Rendering schematic to {}'.format(destination.name))

    json.dump(json.loads(rendered), destination, indent=2, sort_keys=True)


if __name__ == '__main__':
    generate_schematic()
